version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/devcontainers/dotnet:7.0
    steps:
      - checkout
      - run: nuget restore
      - run: dotnet build
      - run: dotnet test 
