version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/devcontainers/dotnet:7.0
      - image: selenium/standalone-chrome:3.11.0
      - image: docker:17.05.0-ce-git
    steps:
      - checkout    
      - setup_remote_docker:
        docker_layer_caching: true
        version: 20.10.12
      # Download and cache dependencies
      - run:
          name: create docker network
          command: docker network create grid
     
      - run:
          name: install selenium-hub
          command: docker run -d --rm -p 4444:4444 --net grid --name selenium-hub selenium/hub:3.11.0
          
      - run:
          name: install selenium-node
          command: docker run -d --rm --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-chrome:3.11.0
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test 
