version: 2.1
jobs:
  build:
    docker:
      - image: docker pull mcr.microsoft.com/dotnet/framework/sdk:4.8.1
    steps:
      - checkout
      - run: nuget restore
      - run: dotnet build
      - run: dotnet test 
