version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.
  browser-tools: circleci/browser-tools@1.4.1


jobs:
  build: # name of your job
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows virtual machine environment
      - run: install Google.Chrome
      - run: dotnet build
      - run: dotnet test
      