version: 2.1 

orbs:
  win: circleci/windows@5.0 

jobs:
  build: 
    executor: win/default 
    working_directory: ~/project


    steps:
      - checkout
      - run:
         name: "Installing chrome browser"
         command: choco install googlechrome -y 
        
      - run:
         name: "Building project"
         command: dotnet build

      - run:
         name: "Starting tests"
         command: dotnet test

      - run:
          name: 'Installing allure report'
          command: |
            iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
            scoop install allure
            echo Allure version: $(allure --version)
            allure generate Qase/bin/Debug/net6.0/allure-results
          when: always

      - store_artifacts:
          path: allure-report
     
      